### ISSUE TITLE
ClassCastException for RedshiftDatabase to liquibase.database.Database

### ISSUE THREAD

**Issue by jessmchung** [liquibase/liquibase-redshift#2]
Hi,

I am trying to setup a pom.xml file to use Liquibase with Redshift. Here is the relevant <code>plugin</code> portion of the pom:
```
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>3.2.2</version>
                <configuration>
                    <changeLogFile>${changeLogFile}</changeLogFile>
                    <driver>org.postgresql.Driver</driver>
                    <url>jdbc:postgresql://${targetdbhost}:${targetdbport}/${targetdb}?tcpKeepAlive=true</url>
                    <username>${username}</username>
                    <password>${password}</password>
                    <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
                    <!-- Not sure if this is how it is supposed to be used-->
                    <databaseClass>liquibase.ext.redshift.database.RedshiftDatabase</databaseClass>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>9.1-901.jdbc4</version>
                    </dependency>
                    <dependency>
                      <groupId>org.liquibase</groupId>
                      <artifactId>liquibase-core</artifactId>
                      <version>3.2.2</version>
                    </dependency>
                    <!--Can liquibase-redshift be added to Maven repository to eliminate the need to add it to classpath?
                    <dependency>
                      <groupId>org.liquibase.ext</groupId>
                      <artifactId>liquibase-redshift</artifactId>
                      <version>1.0</version>
                    </dependency>-->                  
                </dependencies>
            </plugin>
```
In my ~/Library/Java/Extensions directory, I have the liquibase-redshift (release 6) and liquibase (3.2.2) jar files. When I run for the first time, to create the DATABASECHANGELOG and DATABASECHANGELOCK tables, I get the following error:
```
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.2.2:update (default-cli) on project dw.build: Error setting up or running Liquibase: liquibase.exception.DatabaseException: java.lang.ClassCastException: liquibase.ext.redshift.database.RedshiftDatabase cannot be cast to liquibase.database.Database -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.liquibase:liquibase-maven-plugin:3.2.2:update (default-cli) on project dw.build: Error setting up or running Liquibase: liquibase.exception.DatabaseException: java.lang.ClassCastException: liquibase.ext.redshift.database.RedshiftDatabase cannot be cast to liquibase.database.Database
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error setting up or running Liquibase: liquibase.exception.DatabaseException: java.lang.ClassCastException: liquibase.ext.redshift.database.RedshiftDatabase cannot be cast to liquibase.database.Database
	at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:371)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.lang.ClassCastException: liquibase.ext.redshift.database.RedshiftDatabase cannot be cast to liquibase.database.Database
	at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:53)
	at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:320)
	... 21 more
Caused by: liquibase.exception.DatabaseException: java.lang.ClassCastException: liquibase.ext.redshift.database.RedshiftDatabase cannot be cast to liquibase.database.Database
	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:231)
	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:141)
	at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:44)
	... 22 more
Caused by: java.lang.ClassCastException: liquibase.ext.redshift.database.RedshiftDatabase cannot be cast to liquibase.database.Database
	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:173)
	... 24 more
```

Advice? Thank you in advance!

-Jess

**Comment by sarxos** [comment]
Hello @liquibase Heam, 

Thank you for the great library. It really helps me manage my Redshift schema. In regards to:

> Would you be willing to add liquibase-redshift to the Maven repository?

I'm waiting for the artifact in Maven Central as well. It would be really helpful to have it there. :+1:

**Comment by nvoxland** [comment]
Releasing it to maven got wrapped up with a new liquibase 3.3 and a bundle of other plugins I was going to release in one synchronized push. Hoping to get to it today.

**Comment by nvoxland** [comment]
Liquibase-Redshift 1.0 has been pushed to the maven repos now.  I think this original issue may have been a pre-1.0 and/or liquibase version incompatiblity that should be cleared op now with the Liquibase 3.3.2 and Liquibase-Redshift 1.0. If you are still seeing the issue with those versions reopen the ticket.

**Comment by jessmchung** [comment]
@nvoxland Thanks! That fixed my issue. :beers:

**Comment by nvoxland** [comment]
Good. Thanks for the update.
